### ISSUE TITLE
Global Exception Handling

### ISSUE THREAD

**Issue by cdeiac** [UZHASE/bnbexplorer-backend#34]
We need to implement global exception handling, such that we return service errors with appropriate HTTP status and a useful message when exceptions occur. Currently, we have no such thing and return the whole stacktrace as service response.

**Comment by julwil** [comment]
@cdeiac Good thought :)
Generic exception handling is already handled by the framework. This can be controlled by the debug flag in this line:
`app.run(port=8080, debug=False)`
Debug mode: Stacktrace is returned
Prod mode: HTTP Status codes are used (404, 500, ...)

Currently, this was not working due to stupid bug:
`debug=bool(env.get('DEBUG', False))`

So.. this issue can be resolved by fixing the cast issue from string to bool

**Comment by cdeiac** [comment]
I saw that, but I didn't find it particularly useful.
For example, whenever we expect an Integer-input (e.g., an ID) but we get a String, then the service throws a TypeError and returns a generic HTTP 500. 
We should add some basic input validation anyways and then we can return useful error messages.

**Comment by julwil** [comment]
@cdeiac 
Will close this issue as it's already merged.

Create a new one for query parameters: https://github.com/UZHASE/bnbexplorer-backend/issues/43
