### ISSUE TITLE
/listings filter queries support for multiple selection (location, area, roomtype)

### ISSUE THREAD

**Issue by PKiechl** [UZHASE/bnbexplorer-backend#51]
Currently endpoint does not support either `listings?location=Brooklyn,Manhattan` nor `listings?location=Brooklyn&location=Manhattan`. This is the case for all three out of location, area and roomtype.

Maybe there is another form of handling multiple values already implemented, if so, please let us know.

**Comment by cdeiac** [comment]
Currently, it is not supported. There was still a TODO in our code about this matter but I forgot to ask about it in our meeting. 
I will implement it later today, such that we can pass (one or) several values as query parameter for `location, area and roomType`.

Also, how do we want to handle inputs for `listingsPerHost` and `availability` ? 
Currently it is implemented as minimum value (we filter for values that are >= the given value) because we do not have a field for min and max as with price. Should we keep it like this?

**Comment by PKiechl** [comment]
Nice, thx for taking care of it so quickly.

As for `listingsPerHost` and `availability`, it is working fine as is with the minimum value, we don't see the need to additionally impose a maximum as well, so you can keep it this way.
